//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEXPERİENCE
    {
        public int ID { get; set; }
        public string TİTLE { get; set; }
        public string SUBTİTLE { get; set; }
        public string DATE { get; set; }
        public string DETAİLS { get; set; }
    }
}
